version: '3.8'
services:
  database:
    hostname: postgres-hostname
    image: postgres
    container_name: pl-tweet
    volumes:
      - db-data:/var/lib/tweet-postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms_tweet
    ports:
      - "5431:5432"
    networks:
      - ms_network



networks:
  ms_network:
volumes:
  db-data: